version: '3.1'
services:
  mongo:
    image: mongo:4.0.4
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './data/mongodb:/data/db'
    ports:
      - 27017:27017